const currencyOptions = [
  { value: "ARS", label: "Peso Argentino (ARS)", icon: "🇦🇷" },
  { value: "USD", label: "Dólar Estadounidense (USD)", icon: "🇺🇸" },
  { value: "EUR", label: "Euro (EUR)", icon: "🇪🇺" },
  { value: "BRL", label: "Real Brasileño (BRL)", icon: "🇧🇷" },
  { value: "CLP", label: "Peso Chileno (CLP)", icon: "🇨🇱" },
  { value: "COP", label: "Peso Colombiano (COP)", icon: "🇨🇴" },
  { value: "MXN", label: "Peso Mexicano (MXN)", icon: "🇲🇽" },
  { value: "PEN", label: "Sol Peruano (PEN)", icon: "🇵🇪" },
  { value: "UYU", label: "Peso Uruguayo (UYU)", icon: "🇺🇾" },
  { value: "VES", label: "Bolívar Venezolano (VES)", icon: "🇻🇪" },
  { value: "CAD", label: "Dólar Canadiense (CAD)", icon: "🇨🇦" },
  { value: "GBP", label: "Libra Esterlina (GBP)", icon: "🇬🇧" },
  { value: "JPY", label: "Yen Japonés (JPY)", icon: "🇯🇵" },
  { value: "CNY", label: "Yuan Chino (CNY)", icon: "🇨🇳" },
  { value: "AUD", label: "Dólar Australiano (AUD)", icon: "🇦🇺" },
  { value: "CHF", label: "Franco Suizo (CHF)", icon: "🇨🇭" },
  { value: "SEK", label: "Corona Sueca (SEK)", icon: "🇸🇪" },
  { value: "NOK", label: "Corona Noruega (NOK)", icon: "🇳🇴" },
  { value: "DKK", label: "Corona Danesa (DKK)", icon: "🇩🇰" },
  { value: "PLN", label: "Zloty Polaco (PLN)", icon: "🇵🇱" },
  { value: "CZK", label: "Corona Checa (CZK)", icon: "🇨🇿" },
  { value: "HUF", label: "Forint Húngaro (HUF)", icon: "🇭🇺" },
  { value: "RUB", label: "Rublo Ruso (RUB)", icon: "🇷🇺" },
  { value: "INR", label: "Rupia India (INR)", icon: "🇮🇳" },
  { value: "KRW", label: "Won Surcoreano (KRW)", icon: "🇰🇷" },
  { value: "SGD", label: "Dólar de Singapur (SGD)", icon: "🇸🇬" },
  { value: "HKD", label: "Dólar de Hong Kong (HKD)", icon: "🇭🇰" },
  { value: "NZD", label: "Dólar Neozelandés (NZD)", icon: "🇳🇿" },
  { value: "ZAR", label: "Rand Sudafricano (ZAR)", icon: "🇿🇦" },
  { value: "TRY", label: "Lira Turca (TRY)", icon: "🇹🇷" },
  { value: "ILS", label: "Shekel Israelí (ILS)", icon: "🇮🇱" },
  {
    value: "AED",
    label: "Dirham de los Emiratos Árabes Unidos (AED)",
    icon: "🇦🇪",
  },
  { value: "SAR", label: "Riyal Saudí (SAR)", icon: "🇸🇦" },
  { value: "QAR", label: "Riyal Catarí (QAR)", icon: "🇶🇦" },
  { value: "KWD", label: "Dinar Kuwaití (KWD)", icon: "🇰🇼" },
  { value: "BHD", label: "Dinar Bahreiní (BHD)", icon: "🇧🇭" },
  { value: "OMR", label: "Rial Omaní (OMR)", icon: "🇴🇲" },
  { value: "JOD", label: "Dinar Jordaniano (JOD)", icon: "🇯🇴" },
  { value: "LBP", label: "Libra Libanesa (LBP)", icon: "🇱🇧" },
  { value: "EGP", label: "Libra Egipcia (EGP)", icon: "🇪🇬" },
  { value: "MAD", label: "Dirham Marroquí (MAD)", icon: "🇲🇦" },
  { value: "TND", label: "Dinar Tunecino (TND)", icon: "🇹🇳" },
  { value: "DZD", label: "Dinar Argelino (DZD)", icon: "🇩🇿" },
  { value: "NGN", label: "Naira Nigeriana (NGN)", icon: "🇳🇬" },
  { value: "KES", label: "Chelín Keniano (KES)", icon: "🇰🇪" },
  { value: "UGX", label: "Chelín Ugandés (UGX)", icon: "🇺🇬" },
  { value: "TZS", label: "Chelín Tanzano (TZS)", icon: "🇹🇿" },
  { value: "ETB", label: "Birr Etíope (ETB)", icon: "🇪🇹" },
  { value: "GHS", label: "Cedi Ghanés (GHS)", icon: "🇬🇭" },
  {
    value: "XOF",
    label: "Franco CFA de África Occidental (XOF)",
    icon: "🇸🇳",
  },
  {
    value: "XAF",
    label: "Franco CFA de África Central (XAF)",
    icon: "🇨🇲",
  },
];

const countryOptions = [
  { value: "AR", label: "Argentina", icon: "🇦🇷" },
  { value: "BO", label: "Bolivia", icon: "🇧🇴" },
  { value: "BR", label: "Brasil", icon: "🇧🇷" },
  { value: "CL", label: "Chile", icon: "🇨🇱" },
  { value: "CO", label: "Colombia", icon: "🇨🇴" },
  { value: "CR", label: "Costa Rica", icon: "🇨🇷" },
  { value: "CU", label: "Cuba", icon: "🇨🇺" },
  { value: "DO", label: "República Dominicana", icon: "🇩🇴" },
  { value: "EC", label: "Ecuador", icon: "🇪🇨" },
  { value: "SV", label: "El Salvador", icon: "🇸🇻" },
  { value: "GT", label: "Guatemala", icon: "🇬🇹" },
  { value: "HN", label: "Honduras", icon: "🇭🇳" },
  { value: "MX", label: "México", icon: "🇲🇽" },
  { value: "NI", label: "Nicaragua", icon: "🇳🇮" },
  { value: "PA", label: "Panamá", icon: "🇵🇦" },
  { value: "PY", label: "Paraguay", icon: "🇵🇾" },
  { value: "PE", label: "Perú", icon: "🇵🇪" },
  { value: "PR", label: "Puerto Rico", icon: "🇵🇷" },
  { value: "UY", label: "Uruguay", icon: "🇺🇾" },
  { value: "VE", label: "Venezuela", icon: "🇻🇪" },
  { value: "ES", label: "España", icon: "🇪🇸" },
  { value: "US", label: "Estados Unidos", icon: "🇺🇸" },
  { value: "CA", label: "Canadá", icon: "🇨🇦" },
];

export { currencyOptions, countryOptions };
